config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "users/registrations"
  }
  authenticated :user do
   #root to: "events#index", as: "authenticated_root"
   get 'users' => 'users#index'
   get 'sign-in-as' => 'users#sign_in_as'
  end

  resources :events
  resources :reports
  resources :entries

  root 'events#root' # What's the difference between "root" and "root to:""??

  get 'events/:id/picture/:name' => 'events#show_picture', as: 'events_picture'
  get 'events_by/:id' => 'events#index_by_user', as: 'events_by'
  get 'events_pasts' => 'events#pasts', as: 'events_pasts'
  get 'events/:id/dup' => 'events#duplicate', as: 'dup_event'

  get 'entries_toggle' => 'entries#toggle', as: 'entries_toggle'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :event

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name,  presence: true

  scope :active, -> { where active: true }
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  respond_to :html

  def new
    @entry = Entry.new
    @entry.event_id = params[:event_id]
    respond_with(@entry)
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:notice] = 'お申し込みを受け付けました。'
      if session[:entries].nil?
        session[:entries] = {}
      end
      session[:entries][@entry.event_id.to_s] = DateTime.now
      EntryMailer.confirm(@entry).deliver_later
      EntryMailer.notify(@entry).deliver_later
      redirect_to controller: 'events', action: 'show', id: @entry.event_id
    else
      render :new
    end
  end

  def index
    event_id = params[:event_id]
    @event = Event.find(event_id)
    unless current_user.id == @event.user.id
      raise 'This event is not owned by you.'
    end
    @entries = Entry.where(event_id: event_id).order("created_at desc")
  end

  def toggle
    e = Entry.find(params[:id])
    raise "Entry not found for #{params[:id]}." unless e
    e.active = !e.active
    e.save!
    render plain: "OK"
  end

  private
    def entry_params
      params.require(:entry).permit(:event_id, :email, :name, :message)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<h1><%= @event.title %></h1>
<div class="row">
  <div class="col-md-12">
<% if @entries.count == 0 %>
<div class="panel panel-default">
  <div class="panel-body">
    申込はまだありません。
  </div>
</div>
<% else %>
<div class="alert alert-info"><%= @entries.active.count %> 件の申込があります。</div>
<table class="table">
  <thead>
    <tr>
      <th>氏名</th>
      <th>メール</th>
      <th>メッセージ</th>
      <th>登録日時</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.name %></td>
    <td><%= entry.email %></td>
    <td><%= entry.message %></td>
    <td><%= entry.created_at %></td>
    <td><%  if entry.active %><span class='glyphicon glyphicon-ok'></span><% end %></td>
    <td><%  if entry.active %>
      <button class="btn btn-sm btn-warning" onclick="toggle(<%= entry.id %>)">無効にする</button>
        <% else %>
      <button class="btn btn-sm btn-success" onclick="toggle(<%= entry.id %>)">有効に戻す</button>
        <% end %></td>
  </tr>
<% end %>
  </tbody>
</table>
<% end %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-12">
    <%= link_to '一覧に戻る', events_path, class: "btn btn-default" %>
  </div>
</div>
<script>
function toggle(id){
  $.get('entries_toggle',{"id":id},function(d){
    location.reload();
  });
}
</script>

app/views/entries/new.html.erb
<h1><%= @entry.event.title %></h1>

<div class="row">
  <div class="col-md-6">
    <div class="alert alert-info">
      参加人数を把握するための簡易的なものですが、主催者側からメールが返信されることもあります。
      申込後、自動返信メールが正常に届いていることをご確認ください。
    </div>
    <%= form_for(@entry) do |f| %>
    <% if @entry.errors.any? %>
      <div id="error_explanation" class="alert alert-warning">
        <p><%= pluralize(@entry.errors.count, "個") %>のエラー:</p>

        <ul>
        <% @entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :event_id %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_field :message, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit nil,class: "btn btn-primary" %>
      <%= link_to 'イベント情報に戻る', event_path(@entry.event_id), class: 'btn btn-default' %>
    </div>
    <% end %>
  </div>
</div>

app/views/entries/show.html.erb
<h1><%= @entry.event.title %></h1>
<div class="row event-detail">
  <div class="col-md-6">
  </div>
  <div class="col-md-6">
</div>