config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "users/registrations"
  }
  authenticated :user do
   #root to: "events#index", as: "authenticated_root"
   get 'users' => 'users#index'
   get 'sign-in-as' => 'users#sign_in_as'
  end

  resources :events
  resources :reports
  resources :entries

  root 'events#root' # What's the difference between "root" and "root to:""??

  get 'events/:id/picture/:name' => 'events#show_picture', as: 'events_picture'
  get 'events_by/:id' => 'events#index_by_user', as: 'events_by'
  get 'events_pasts' => 'events#pasts', as: 'events_pasts'
  get 'events/:id/dup' => 'events#duplicate', as: 'dup_event'

  get 'entries_toggle' => 'entries#toggle', as: 'entries_toggle'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :entries
  validates :title, presence: true
  validates :opendate, presence: true
  validates :address_title, presence: true
  #validates :picture_main, presence: true

  def opendate_short
    if opendate.year == Date.today.year
      d = opendate.strftime("%m/%d")
    else
      d = opendate.strftime("%Y/%m/%d")
    end
    w = %w(日 月 火 水 木 金 土)[opendate.wday]
    d+" ("+w+") "+(opendate_memo == nil ? "" : opendate_memo)
  end

  def limit_short
    return "なし" if limit == nil || limit == 0
    return "#{limit} 名"
  end

  def fee_short
    return "無料" if fee.nil? || fee <= 0
    return "#{fee} 円"
  end

  def ended?
    opendate < Date.today
  end

  def full?
    return false if limit.nil? || limit <= 0
    return entries.active.count >= limit
  end

  def address_title_with_url
    return address_title if address_url.blank?
    if address_url.start_with? "http"
      u = address_url
    else
      u = "https://places.lmlab.net/#{address_url}/access"
    end
    return "<a href='#{u}' target='_blank'>#{address_title}</a>".html_safe
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :show_picture, :duplicate]
  before_action :authenticate_user!, except: [:root, :pasts, :show, :show_picture, :index_by_user]

  respond_to :html

  def root
    cond = build_condition(params[:q])
    logger.debug(cond)
    @events = Event.where(cond+"opendate >= ? AND visible = true",Date.today.to_s).order("opendate").limit(100)
    @events = divide(@events,3)
    @all = params[:all]
    respond_with(@events)
  end

  def index
    # Use for user home
    @upcomings = Event.where("opendate >= ? AND user_id = ?",Date.today.to_s,current_user.id).order("opendate ASC")
    @ends = Event.where("opendate < ? AND user_id = ?",Date.today.to_s,current_user.id).order("opendate DESC")
    respond_with(@upcomings,@ends)
  end

  def index_by_user
    title = params[:title] || ""
    title.gsub!(/'%/,"")
    @user = User.find(params[:id])
    raise ActionController::RoutingError.new('User not found.') unless @user
    @upcomings = Event.where("opendate >= ? AND user_id = ? AND visible = true AND title like '#{title}%'",Date.today.to_s,@user.id).order("opendate ASC")
    @ends = Event.where("opendate < ? AND user_id = ? AND visible = true",Date.today.to_s,@user.id).order("opendate DESC")
    if request.format == "html"
      @upcomings = divide(@upcomings,3)
      @ends = divide(@ends,3)
    end
  end

  def pasts
    @ends = Event.where("opendate < ? AND visible = true",Date.today.to_s).order("opendate DESC").limit(100)
    @ends = divide(@ends,3)
    respond_with(@ends)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    @event.user_id = current_user.id
    respond_with(@event)
  end

  def edit
    if current_user.id != @event.user_id
      raise ActionController::RoutingError.new('This event is not yours.')
    end
  end

  def duplicate
    if current_user.id != @event.user_id
      raise ActionController::RoutingError.new('This event is not yours.')
    end
    #@event.id = nil
    @event.visible = false # Always invisible after duplication.
  end

  def create
    @event = Event.new(event_params)
    if params[:event][:id]
      # from duplicate
      orig = Event.find(params[:event][:id])
      @event.picture_main = orig.picture_main
      @event.picture_1 = orig.picture_1
      @event.picture_2 = orig.picture_2
      @event.picture_3 = orig.picture_3
    end
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  def show_picture
    n = "picture_"+ (params["name"] || "main")
    d = @event.send(n)
    if d
      send_data d, :type => 'image/jpeg', :disposition => "inline"
    else
      raise ActionController::RoutingError.new('Picture of '+@event.title+' '+n+' not found')
    end
  end

  private
    # 指定した列数に分割
    def divide(events,n_rows=3)
      event_rows = Array.new(n_rows) { [] }
      events.each_with_index do |e,i|
        event_rows[i % n_rows] << e
      end
      event_rows
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def adjust_image(b)
      require 'RMagick'
      i = Magick::Image.from_blob(b.read)[0]
      if i.columns > 1024
        return i.resize(0.5).to_blob
      else
        return i.to_blob
      end
    end

    def build_condition(q)
      return "" if q.blank?
      qs = q.gsub(/['"%]/,"").split(/ +/)
      cs = []
      qs.each do |q1|
        if q1.include? ":"
          k,v = q1.split(":")
          if k == "date"
            d = Date.parse(v).strftime("%Y-%m-%d")
            cs += ["opendate = '#{d}'"]
          end
        else
          # キーワードだけの場合は、タイトルと住所を検索
          cs += ["(title like '%#{q1}%' or address like '%#{q1}%')"]
        end
      end
      return "("+cs.join(" and ")+") and "
    end

    def event_params
      p = params.require(:event).permit(:user_id, :title, :opendate, :opendate_memo,
       :address_title, :address, :postal, :address_embed, :fee, :fee_memo, :limit,
        :desc_short, :desc_long, :picture_main, :picture_1, :picture_2, :picture_3,
         :url, :url_facebook, :url_twitter, :visible, :host, :has_entry,
         :address_memo, :address_url)
      [:picture_main,:picture_1,:picture_2,:picture_3].each do |k|
        # 大きすぎる画像は小さくする
        p[k] = adjust_image(p[k]) if p[k]
      end
      if p[:address_embed].present? && p[:address_embed].start_with?("<iframe ")
        # iframeタグが貼られていたらsrc属性だけ取り出して保存
        p[:address_embed] = (p[:address_embed].match /src="(.+)"/)[1]
      end
      return p
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_ad1.html.erb
<div class="event">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- events.lmlab.net -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-2854141448142469"
       data-ad-slot="6544720452"
       data-ad-format="auto"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/events/_event.html.erb
<div class="event <%= "hidden-xs" if !@all && index > 0 %>">
  <%= link_to image_tag(events_picture_path(event.id,"main")), event %>
  <h3><%= link_to event.title, event %></h3>
  <p>
    <span class="glyphicon glyphicon-time" title="開催日"></span> <%= event.opendate_short %><br/>
    <span class="glyphicon glyphicon-map-marker" title="場所"></span> <%= event.address_title_with_url %><br/>
    <span class="glyphicon glyphicon-user" title="主催者"></span>
    <% if event.host.present? %>
      <%= event.host %>
      <small>(via <%= link_to event.user.name,events_by_path(event.user) %>)</small>
    <% else %>
      <%= link_to(event.user.name,events_by_path(event.user)) if event.user %>
    <% end %>
  </p>
</div>

app/views/events/_form.html.erb
<% f = @f %>
  <% if @event.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <p><%= pluralize(@event.errors.count, "error") %>個のエラー:</p>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :opendate %>
    <%= f.date_field :opendate, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :opendate_memo %>
    <%= f.text_field :opendate_memo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address_title %>
    <%= f.text_field :address_title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address_url %>
    <%= f.text_field :address_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :postal %>
    <%= f.text_field :postal, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address_memo %>
    <%= f.text_field :address_memo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address_embed %>
    <%= f.text_field :address_embed, class: "form-control" %>
    <small>Google Map(Embed Map)のiframeタグsrc部分を貼り付けて下さい。</small>
  </div>
  <div class="form-group">
    <%= f.label :fee %>
    <%= f.number_field :fee, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :fee_memo %>
    <%= f.text_field :fee_memo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :limit %>
    <%= f.number_field :limit, class: "form-control" %>
    <small>定員なしの場合、0に設定してください。</small>
  </div>
  <div class="form-group">
    <%= f.label :desc_short %>
    <%= f.text_area :desc_short, class: "form-control" %>
    <small>80文字程度推奨。 <span id="n_desc_short">0</span></small>
    <script>
      $("#event_desc_short").keyup(function(e){
        $("#n_desc_short").text($(e.target).val().length);
      });
      $("#n_desc_short").text($(e.target).val().length);
    </script>
  </div>
  <div class="form-group">
    <%= f.label :desc_long %>
    <%= f.text_area :desc_long, rows: 10, class: "form-control" %>
    <small>500~1000文字程度推奨。 <span id="n_desc_long">0</span></small>
    <script>
      $("#event_desc_long").keyup(function(e){
        $("#n_desc_long").text($(e.target).val().length);
      });
      $("#n_desc_long").text($(e.target).val().length);
    </script>
  </div>
  <div class="form-group">
    <%= f.label :picture_main %>
    <%= f.file_field :picture_main, class: "form-control" %>
    <small>幅600px程度</small>
  </div>
  <div class="form-group">
    <%= f.label :picture_1 %>
    <%= f.file_field :picture_1, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :picture_2 %>
    <%= f.file_field :picture_2, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :picture_3 %>
    <%= f.file_field :picture_3, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url_facebook %>
    <%= f.text_field :url_facebook, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url_twitter %>
    <%= f.text_field :url_twitter, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :host, "主催者" %>
    <%= f.text_field :host, class: "form-control" %>
    <small>登録者自身が主催のイベントの場合、空のままにしてください。</small>
  </div>
  <div class="form-group">
    <%= f.label :user_id, "登録者" %>
    <%= @event.user.name %>
    <%= f.hidden_field :user_id %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :has_entry %>申込みフォームを付ける
    </label>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :visible %>公開する
    </label>
  </div>
  <div class="actions">
    <%= f.submit nil,class: "btn btn-primary" %>
  </div>

app/views/events/_index_event.html.erb
<table class="table">
  <thead>
    <tr>
      <th>開催日</th>
      <th>場所</th>
      <th>タイトル</th>
      <th>参加費</th>
      <th>定員</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <% if event.visible %>
      <tr>
      <% else %>
      <tr style="background-color: #eee;">
      <% end %>
      <td><%= event.opendate_short %></td>
      <td><%= event.address_title %></td>
      <td><%= event.title %></td>
      <td><%= event.fee %></td>
      <td><%= event.limit %></td>
      <td><%= link_to '閲覧', event, class: "btn btn-default" %>
      <%= link_to '編集', edit_event_path(event), class: "btn btn-default" %>
      <%= link_to '削除', event, method: :delete, data: { confirm: 'よろしいですか?' }, class: "btn btn-danger" %>
      <%= link_to '複製', dup_event_path(event), class: "btn btn-default" %>
      <% if event.has_entry %>
        <% n_entry = event.entries.active.count %>
        <%= link_to ('申込 <span class="badge">'+n_entry.to_s+'</span>').html_safe, entries_path(event_id: event.id), class: "btn btn-default" %>
      <% else %>
        <%= link_to '申込', "#", class: "btn btn-default disabled" %>
      <% end %>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/duplicate.html.erb
<h1>複製</h1>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@event, url: events_path, method: :post) do |f| %>
    <%= f.hidden_field :id %>
    <% @f = f %>
    <%= render 'form' %>
    <% end %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-6">
    <%= link_to '一覧に戻る', events_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>編集</h1>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@event) do |f| %>
    <% @f = f %>
    <%= render 'form' %>
    <% end %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-6">
<%= link_to '閲覧', @event, class: 'btn btn-default' %>
<%= link_to '一覧に戻る', events_path, class: 'btn btn-default' %>

  </div>
</div>

app/views/events/index.html.erb
<p>ようこそ <%= current_user.name %> さん
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete  %>
</p>
<p>
  <%= link_to '新しいイベントを登録する', new_event_path, class: "btn btn-primary" %>
  <%= link_to 'ユーザ情報を変更する', edit_user_registration_path, class: "btn btn-default" %>
  <%= link_to 'ユーザ一覧', users_path, class: "btn btn-default" if current_user.admin? %>
</p>
<h3>近日開催</h3>
<%= render partial: "index_event", locals: {events: @upcomings} %>

<h3>開催済み</h3>
<%= render partial: "index_event", locals: {events: @ends} %>

app/views/events/index_by_user.html.erb
<h1><%= @user.name %> のイベント</h1>
<h3>近日開催</h3>
<div class="row">
  <% @upcomings.each do |col| %>
    <div class="col-sm-4">
      <% col.each_with_index do |event,j| %>
        <%= render partial: 'event', locals: {event: event,index: j} %>
      <% end %>
    </div>
  <% end %>
</div>
<h3>開催済み</h3>
<div class="row">
  <% @ends.each do |col| %>
    <div class="col-sm-4">
      <% col.each_with_index do |event,j| %>
        <%= render partial: 'event', locals: {event: event,index: j} %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/pasts.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>開催済み</h2>
  </div>
  <div class="col-md-6 text-right">
    <%= link_to 'トップページ', root_path, class: 'btn btn-default' %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= render "ad1" %>
  </div>
</div>
<div class="row">
  <% @ends.each do |col| %>
    <div class="col-sm-4">
      <% col.each_with_index do |event,i| %>
        <%= render partial: 'event', locals: {event: event,index: i} %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-md-12 text-right">
    <%= link_to 'トップページ', root_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/events/root.html.erb
<div class="row">
  <% if @events.empty? %>
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          開催予定のイベントはありません。
        </div>
      </div>
    </div>
  <% else %>
    <% @events.each_with_index do |col,i| %>
      <div class="col-sm-4">
        <% col.each_with_index do |event,j| %>
          <%= render partial: 'event', locals: {event: event,index: j} %>
        <% end %>
        <%= render 'ad1' if i == 2 %>
      </div>
    <% end %>
    <div class="col-sm-12 visible-xs"><%= link_to 'もっと見る', root_path(all: true), class: 'btn btn-default' unless @all %></div>
  <% end %>
</div>
<div class="row">
  <div class="col-md-12 text-right">
    <%= link_to '開催済みのイベント', events_pasts_path, class: 'btn btn-default' %>
  </div>
</div>
<div class="row paper">
  <div class="col-md-6">
    <h2>このサイトについて <small>About this site</small></h2>
    <p>「360 Board」では、シンプルなイベント告知ページを作ることができます。</p>
    <p>SNS等でのイベント告知のランディングページとしての利用を想定しています。
      目的・ジャンルを問わず、様々なタイプのイベントの告知にお使い頂けます。
      細かい規約は設けていませんが、良識のある利用をお願い致します（不適切と判断した投稿は予告なく削除することがあります）。</p>
    <p>Ruby on Railsの勉強会で作った習作に手を加えて公開しています。
      ソースコードは<a href="https://github.com/lumbermill/events.lmlab.net">GitHubで公開</a>していますので、
      自由にフォークして独自のサイト作りに役立てて頂いても構いません。機能追加のリクエストや不具合報告も歓迎します。</p>
    <p>
      <%= link_to (image_tag "360.png", style: "width: 76px; float: left; margin-right: 20px"), "https://360.lmlab.net", target: "_blank"%>
      「<%= link_to "360 Cafe&Bar", "https://360.lmlab.net", target: "_blank" %>」は、
      誰でも日替りで飲食店（カフェ＆バー）の店長になれるお店です。このお店に集まったイベント情報を掲載するために使用していたところが最初です。
      2017年11月から、「<%= link_to "360 Places", "https://places.lmlab.net", target: "_blank" %>」をオープンしています。
      こちらは、シェア型のスペース情報をまとめたサイトで、ここに掲載したイベントの会場などを登録しています。
    </p>
</div>
<div class="col-md-6">
  <h3>イベント情報を探している方へ <small>To visitors</small></h3>
  <p>一部の情報はネットの情報を収集して転載したものです（各詳細ページに注意書き、一覧ページに「via..」と表記があるもの）。
    主催者の発信する情報が更新されて齟齬が生じる可能性があります。<b>必ず主催者が直接発信する一次情報を確認してください。</b>
  </p>
  <p>
    掲載ユーザ毎の未開催のイベントをJSON形式で返すAPIを提供しています。ご自身のサイトやアプリに連動する際に利用できます。
  </p>
  <pre><a href="events_by/3.json">events_by/3.json</a></pre>
  <h3>掲載を希望される方へ <small>To event owners</small></h3>
  <p>以下のいずれかの方法をご利用ください。</p>
  <ol>
    <li>右上の「ユーザ登録」からアカウント作成をすると、管理画面へとアクセスすることができるようになります。
      「新しいイベントを登録する」からご自身のイベントを登録することができます。</li>
    <li><%= link_to "360", "https://360.lmlab.net", target: "_blank" %>のお店まで、チラシ等をお持ちください。掲載を代行致します。</li>
    <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSd_KhEbCgMSZaTGvhmGVct9PMHL53pJJVgIm0qtjoQdsHsiEA/viewform" target="_blank">掲載リクエストフォーム</a></li>
  </ol>
  <p><small>2.3.は単発のイベントに限ります。可能な限り、1.の方法でご自身で管理頂くようお願い致します。</small></p>
  <!--
    望まない情報が掲載されてしまった方へ
  -->
</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<div class="row event-detail">
  <div class="col-md-6">
    <p><%= @event.desc_short.gsub("\n","<br/>").html_safe %></p>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= @event.desc_long.gsub("\n","<br/>").html_safe %>
      </div>
    </div>
    <table class="table event">
      <tr>
        <th><span class="glyphicon glyphicon-time"></span> 日時</th>
        <td><%= @event.opendate_short %>
          <% if @event.ended? %>
          <small class="small-alert">このイベントは開催済みです。</small>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><span class="glyphicon glyphicon-map-marker"></span> 場所</th>
        <td><%= @event.address_title_with_url %><br/>
        <small><%= @event.postal %> <%= @event.address %></small>
        <% if @event.address_memo %>
          <br/><small><%= @event.address_memo %></small>
        <% end %>
        </td>
      </tr>
      <tr>
        <th style="white-space: nowrap"><span class="glyphicon glyphicon-user"></span> 主催者</th>
        <td>
          <% if @event.host.present? %>
            <%= @event.host %>
            <small class="small-alert">このイベントは <%= link_to @event.user.name, events_by_path(@event.user.id) %>
              によってこのサイトに掲載されています。<br/>最新情報は主催者が発信する情報をお確かめください。
            </small>
          <% else %>
            <%= link_to @event.user.name, events_by_path(@event.user.id) %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><span class="glyphicon glyphicon-yen"></span> 参加費</th>
        <td><%= @event.fee_short %><br/><small><%= @event.fee_memo %></small></td>
      </tr>
      <tr>
        <th><span class="glyphicon glyphicon-plus"></span> 定員</th>
        <td><%= @event.limit_short %></td>
      </tr>
      <tr>
        <th>URL</th>
        <td>
          <%= (link_to @event.url, @event.url) if @event.url %><br/>
          <%
          f = image_tag '/images/facebook.png', class: "icon"
          t = image_tag '/images/twitter.png', class: "icon"
          %>
          <%= link_to f, @event.url_facebook if @event.url_facebook.present? %>
          <%= link_to t, @event.url_twitter if @event.url_twitter.present? %>
        </td>
      </tr>
    </table>
    <% if session[:entries] && session[:entries][@event.id.to_s] %>
      <p><button class="btn btn-lg btn-block disabled">申込み済みです</button></p>
      <p>キャンセルは、直接主催者にお問い合わせください。</p>
    <% elsif @event.has_entry && !@event.ended? %>
      <% if @event.full? %>
        <p><button class="btn btn-lg btn-block disabled">定員に達しました</button></p>
      <% else %>
        <p><%= link_to "<span class='glyphicon glyphicon-edit'></span> 申込み".html_safe, new_entry_path(event_id: @event.id), class: "btn btn-success btn-lg btn-block" %></p>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= image_tag events_picture_path(@event.id,"main"), class: "img-rounded" %>
    <br/><br/>
    <div class="row">
      <div class="col-md-4">
        <%= (link_to (image_tag events_picture_path(@event.id,"1"), class: "img-rounded"), events_picture_path(@event.id,"1")) if @event.picture_1 %>
      </div>
      <div class="col-md-4">
        <%= (link_to (image_tag events_picture_path(@event.id,"2"), class: "img-rounded"), events_picture_path(@event.id,"2")) if @event.picture_2 %>
      </div>
      <div class="col-md-4">
        <%= (link_to (image_tag events_picture_path(@event.id,"3"), class: "img-rounded"), events_picture_path(@event.id,"3")) if @event.picture_3 %>
      </div>
    </div>
    <br/>
    <% if @event.address_embed.present? %>
      <iframe src="<%= @event.address_embed %>" width="100%" height="360px"></iframe>
    <% end %>
  </div>
</div>
<hr/>
<% if user_signed_in? && current_user.id == @event.user_id %>
<div class="row">
  <div class="col-md-12">
    <%= link_to '編集', edit_event_path(@event), class: "btn btn-default" %>
    <%= link_to '一覧に戻る', events_path, class: "btn btn-default" %>
  </div>
</div>
<% end %>