config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "users/registrations"
  }
  authenticated :user do
   #root to: "events#index", as: "authenticated_root"
   get 'users' => 'users#index'
   get 'sign-in-as' => 'users#sign_in_as'
  end

  resources :events
  resources :reports
  resources :entries

  root 'events#root' # What's the difference between "root" and "root to:""??

  get 'events/:id/picture/:name' => 'events#show_picture', as: 'events_picture'
  get 'events_by/:id' => 'events#index_by_user', as: 'events_by'
  get 'events_pasts' => 'events#pasts', as: 'events_pasts'
  get 'events/:id/dup' => 'events#duplicate', as: 'dup_event'

  get 'entries_toggle' => 'entries#toggle', as: 'entries_toggle'
end

app/views/layouts/_google.html.erb
<!-- Google Analytics code for lmlab.net -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-27637383-4', 'auto');
ga('send', 'pageview');

</script>

app/views/layouts/_google_ad.html.erb
<div class="row">
	<div class="col-xs-12 google-ad">

		<!-- Google Analitics -->
		<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-27637383-4', 'auto');
		ga('send', 'pageview');

		</script>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to image_tag("360-64.png"), root_path, class: "navbar-brand" %>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<form class="navbar-form navbar-left" action="/">
        <div class="form-group">
          <input name="q" value="<%= params[:q] %>" type="text" class="form-control" placeholder="開催地などで検索">
        </div>
        <button type="submit" class="btn btn-default btn-success"><span class='glyphicon glyphicon-search'></span></button>
      </form>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to "<span class='glyphicon glyphicon-home'></span>".html_safe, events_path %></li>
				<% else %>
					<li><%= link_to '<span class="glyphicon glyphicon-edit"></span> ユーザ登録'.html_safe , new_user_registration_path %></li>
					<li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> ログイン'.html_safe, new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if isEventPage? %>
    <title><%= @event.title %> - <%= @event.host.present? ? @event.host : @event.user.name %></title>
    <meta property="og:title" content="<%= @event.title %> - <%= @event.host.present? ? @event.host : @event.user.name %>">
    <meta property="og:site_name" content="360 Board">
    <meta property="og:description" content="<%= @event.desc_short %>">
    <meta property="og:image" content="<%= events_picture_url(@event.id,"main") %>">
    <meta name="description" content="<%= @event.desc_short %>"/>
    <meta name="keywords" content="<%= @event.opendate_short %>,<%= @event.address_title %>,<%= @event.user.name %>" />
  <% else %>
    <title>360 Board</title>
    <meta property="og:title" content="360 Board">
    <meta property="og:site_name" content="360 Board">
    <meta property="og:description" content="「360 Board」では、シンプルなイベント告知ページを作ることができます。目的・ジャンルを問わず、様々なタイプのイベントの告知にお使い頂けます。">
    <meta property="og:image" content="<%= image_url("360.png") %>">
    <meta name="description" content="「360 Board」では、シンプルなイベント告知ページを作ることができます。目的・ジャンルを問わず、様々なタイプのイベントの告知にお使い頂けます。"/>
    <meta name="keywords" content="360,bulletin board,event,イベント,掲示板,告知,情報,<%= params[:q] %>" />
  <% end %>
  <meta property="og:url" content="<%= request.url %>" />
  <%= javascript_include_tag 'application' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="fb-root"></div>
  <script>
  ( function(d, s, id) {
    var js,
    fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id))
      return;
      js = d.createElement(s);
      js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1471100926452630&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-warning"><%= alert %></p>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-danger" role="alert">
          勉強会の開催情報は新しいサイト(
          <%= link_to 'dojo.lmlab.net', "https://dojo.lmlab.net", class: 'alert-link' %>
          )に移行しました。今後の開催予定の確認・お申込は新サイトからお願い致します。
          2018.05.03
        </div>
      </div>
    </div>
    <%= yield %>
    <%= render 'layouts/google_ad' %>
  </div>
  <footer class="footer">
    <div class="container">
      <a href="https://github.com/lumbermill/events.lmlab.net">GitHub</a>
      &nbsp;
      <a href="https://lmlab.net">Lmlab.net.</a>
    </div<
  </footer>
</body>
</html>